typography_spectrum: 0.4621895846458023
color:
  brandStrength: 0.383889021198588
  lightness: 0.8692527868092466
  saturation: 0.7161330604136432
  rhythmicContrast: 0.5295998067178275
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
layout_spectrum: 0.9960720571736335
author:
  name: テスト
  email: テストテストとともに
  url: 'http://givemethe.link/'
name: giveitago
navigation:
  - name: rusko
    id: 0f27ddc6-2b37-4a6c-92ba-7c07860f3ae6
    type: content
title: give me the link
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/8e13baa6106ee2cd18d00635642b4ee62bf6c020.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/8e13baa6106ee2cd18d00635642b4ee62bf6c020.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/5d35c3f3a1a0a13b7f6a9a1358b1d3fa/croprotate.jpg?cropheight=360&cropwidth=384&degrees=0&input=https%3A%2F%2Fimg.youtube.com%2Fvi%2Fy4cikEmEUms%2Fhqdefault.jpg&x=48&y=0
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: just give it a go
purpose:
  - type: internal
    label: we'll make it happen like you just don't know
    item: 0f27ddc6-2b37-4a6c-92ba-7c07860f3ae6
  - type: contact
    url: 'tel:2222222'
    label: Call 2222222
github: true
content_rating:
  adult: false
